package CoordinatorResourceCommunication;


/**
* CoordinatorResourceCommunication/_CoordinatorInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorResourceCommunication.idl
* Sexta-feira, 27 de Janeiro de 2017 12h19min21s GFT
*/

public class _CoordinatorInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements CoordinatorResourceCommunication.CoordinatorInterface
{

  public void requestResource (String pId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("requestResource", true);
                $out.write_string (pId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                requestResource (pId        );
            } finally {
                _releaseReply ($in);
            }
  } // requestResource

  public void releaseResource ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("releaseResource", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                releaseResource (        );
            } finally {
                _releaseReply ($in);
            }
  } // releaseResource

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CoordinatorResourceCommunication/CoordinatorInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CoordinatorInterfaceStub
