package CoordinatorResourceCommunication;


/**
* CoordinatorResourceCommunication/CoordinatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorResourceCommunication.idl
* Sexta-feira, 27 de Janeiro de 2017 12h19min21s GFT
*/

public interface CoordinatorInterfaceOperations 
{
  void requestResource (String pId);
  void releaseResource ();
} // interface CoordinatorInterfaceOperations
