package CoordinatorResourceCommunication;


/**
* CoordinatorResourceCommunication/CoordinatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorResourceCommunication.idl
* Segunda-feira, 30 de Janeiro de 2017 20h55min46s GFT
*/

public interface CoordinatorInterface extends CoordinatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CoordinatorInterface
