package CoordinatorResourceCommunication;


/**
* CoordinatorResourceCommunication/CoordinatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorResourceCommunication.idl
* Segunda-feira, 30 de Janeiro de 2017 20h55min46s GFT
*/

public interface CoordinatorInterfaceOperations 
{
  void requestResource (String pId);
  void releaseResource ();
  void registerId (org.omg.CORBA.StringHolder pId);
} // interface CoordinatorInterfaceOperations
