package CoordinatorResourceCommunication;

/**
* CoordinatorResourceCommunication/CoordinatorInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorResourceCommunication.idl
* Sexta-feira, 27 de Janeiro de 2017 12h19min21s GFT
*/

public final class CoordinatorInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CoordinatorResourceCommunication.CoordinatorInterface value = null;

  public CoordinatorInterfaceHolder ()
  {
  }

  public CoordinatorInterfaceHolder (CoordinatorResourceCommunication.CoordinatorInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CoordinatorResourceCommunication.CoordinatorInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CoordinatorResourceCommunication.CoordinatorInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CoordinatorResourceCommunication.CoordinatorInterfaceHelper.type ();
  }

}
