package ProcessResourceCommunication;


/**
* ProcessResourceCommunication/ProcessInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProcessResourceCommunication.idl
* Sábado, 28 de Janeiro de 2017 10h57min53s GFT
*/

public abstract class ProcessInterfacePOA extends org.omg.PortableServer.Servant
 implements ProcessResourceCommunication.ProcessInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("concedeResource", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ProcessResourceCommunication/ProcessInterface/concedeResource
       {
         this.concedeResource ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProcessResourceCommunication/ProcessInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ProcessInterface _this() 
  {
    return ProcessInterfaceHelper.narrow(
    super._this_object());
  }

  public ProcessInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ProcessInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ProcessInterfacePOA
