package ProcessResourceCommunication;


/**
* ProcessResourceCommunication/ProcessInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ProcessResourceCommunication.idl
* Sábado, 28 de Janeiro de 2017 10h57min53s GFT
*/

public interface ProcessInterfaceOperations 
{
  void concedeResource ();
} // interface ProcessInterfaceOperations
